name: ✨ Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your ideas for improving the molecular structure animation project.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting this feature request
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested before
          required: true
        - label: I have reviewed the [README](https://github.com/yuis-ice/molecular-structure-animation/blob/main/README.md) and current features
          required: true
        - label: This feature request is related to the molecular structure animation project
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: 🎯 Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: Summarize your feature request in 1-2 sentences...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: 📂 Category
      description: Which category does this feature belong to?
      options:
        - Molecular Visualization
        - Animation Controls
        - User Interface
        - Performance
        - Educational Features
        - Export/Import
        - Accessibility
        - Mobile/Responsive
        - Scientific Accuracy
        - Developer Experience
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 🤔 Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: 🔄 Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🛠️ Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Moderate - Requires some new code/logic
        - Complex - Significant changes needed
        - Very Complex - Major architectural changes
        - Unknown - I'm not sure
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🎓 Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        Describe how you would use this feature:
        - As a student studying chemistry...
        - As an educator teaching molecular structures...
        - As a researcher analyzing compounds...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Examples
      description: If applicable, add mockups, sketches, or examples from other applications
      placeholder: Drag and drop images or describe visual examples...

  - type: textarea
    id: technical-considerations
    attributes:
      label: ⚙️ Technical Considerations
      description: Any technical details, requirements, or constraints to consider
      placeholder: |
        - Performance implications
        - Browser compatibility requirements
        - Data format considerations
        - Integration with existing features
        - etc.

  - type: dropdown
    id: target-users
    attributes:
      label: 👥 Target Users
      description: Who would benefit most from this feature?
      multiple: true
      options:
        - Students
        - Educators/Teachers
        - Researchers
        - Developers
        - General Public
        - Mobile Users
        - Accessibility Users
        - Power Users

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or relevant information about the feature request
      placeholder: Any additional information that might help us understand your request...

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you be interested in contributing to implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false